## Лабораторна робота №2
1.Виконати набір вправ. Всі завдання виконати 2 способами:
* а)з використанням універмальних функцій бібліотеки NumPy
* В)за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).
* с) для обох випадків підрахувати час виконання скрипту та зробити висновок
***
Варіант 6:1,3,4,6,10,12,15,17,18

Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по
діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [1]:
%%timeit
#упражнение 1
n = 5
a = [[0] * n for i in range(n)]
for i in range(n):
    a[i][i] = (i+1)
a

2.07 µs ± 46.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [2]:
%%timeit
#упражнение 1 numPy
import numpy as np
n = 5
np.diag(np.arange(1,n)+1)

5.48 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в
якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші
елементи дорівнюють 1.

In [3]:
%%timeit
#упражнение 3
n,m,r,c = 6,7,2,3
a = [[1] * m for i in range(n)]
for i in range(n):
    for j in range(m):
        if(i % r == 0):
            a[i][j] = 0
        if(j%c == 0):
            a[i][j] = 0
a

12.5 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%%timeit
#упражнение 3 numpy
import numpy as np
n,m,r,c = 6,7,2,3
a = np.ones((n,m),dtype = int)
for i in range(n):
    for j in range(m):
        if(i % r == 0):
            a[i][j] = 0
        if(j%c == 0):
            a[i][j] = 0
a

22.3 µs ± 420 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Вправа 4. Вводяться числа n і m. Вивести масив розміру n на m, в якому у
першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m-1, а всі
інші елементи матриці дорівнюють 0.

In [5]:
%%timeit
#упраженение 4 
n,m = 10,10
a = [[1] * n for i in range(m)]
for i in range(n):
    a[0][i] = i
a

3.13 µs ± 51.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%%timeit
#упраженение 4  numpy
import numpy as np
n,m = 10,10
a = np.zeros((n,m),dtype = int)
a[0] = np.arange(m)
a

2.29 µs ± 46 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на - 1.

In [7]:
%%timeit
#упражнение 6
a = [1,2,3,4,5,0,0,0,-6,-3,-9,9,0,0,0,4]
for i in range(len(a)):
    if(a[i]!=0):
        a[i] = -1
a

1.82 µs ± 59.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
%%timeit
#упражнение 6 numpy
import numpy as np
a = np.array([1,2,3,4,5,0,0,0,-6,-3,-9,9,0,0,0,4])
np.where(a!= 0, -1, 0)

5.86 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вправа 10. Вводиться числа n i m. Створити масив випадкових значень n на m
і обчислити мінімальне, максимальне значення, середнє та середньо
квадратичне відхилення, округлене до 3 знаків після коми

In [9]:
%%timeit
#упражнение 10 numpy
import numpy as np
import math
s = int(0)
n,m = 10,10
a  = np.random.random((n,m))
for i in range(n):
    for j in range(m):
        s += a[i][j] ** 2 
#print("max: ",np.max(a))
#print("min: ", np.min(a))
#print("avg: ", np.sum(a)/(n*m))
#print("avg**2: ",math.sqrt(s/(n*m)))  

82.9 µs ± 1.55 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
%%timeit
#упражнение 10       
import numpy as np
import math
import random
s = int(0)
n,m = 10,10
a  = [[random.random() for j in range(m)] for i in range(n)]
for i in range(n):
    for j in range(m):
        s += a[i][j] ** 2 
#print("max: ",np.max(a))
#print("min: ", np.min(a))
#print("avg: ", np.sum(a)/(n*m))
#print("avg**2: ",math.sqrt(s/(n*m)))  

52.3 µs ± 1.07 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Вправа 12. Створити масив одиниць розміром n х n та створити в ньому
«рамку», сформовану з 0.

In [11]:
%%timeit
import numpy as np
#упражнение 12 numpy
n = int(10)
a = np.ones((n,n),dtype = int)
for i in range(n):
    a[0][i],a[n-1][i],a[i][0],a[i][n-1] = 0,0,0,0
a

14.8 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%%timeit
#упражнение 12
n = int(10)
a = [[1] * n for i in range(n)]
for i in range(n):
    a[0][i],a[n-1][i],a[i][0],a[i][n-1] = 0,0,0,0
a

6.24 µs ± 254 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вправа 15. Заповнити парні стовбчики матриці розміром n х n одиницями, а
непарні – нулями.

In [13]:
%%timeit
import numpy as np
#упражнение 15 numpy
n = 10
a = np.zeros((n,n),dtype = int)
for i in range(n):
    a[i][1::2] = 1
a

7.31 µs ± 123 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%%timeit
#упражнение 15
n = 10
a = [[0] * n for i in range(n)]
for i in range(n):
    for j in range(n):
        if(j % 2 != 0):
            a[i][j] = 1
a

15.9 µs ± 1.32 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вправа 17. Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх
значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [15]:
%%timeit
#упражнение 17 numpy
import numpy as np
n = int(10)
a = np.arange(n)
for i in range(n):
    if(a[i] < n/2 or a[i] > ((3*n)/4)):
        a[i] = -a[i]
a

26.5 µs ± 441 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [16]:
%%timeit
#упражнение 17
n = int(10)
a = [m for m in range(n)]
for i in range(n):
    if(a[i] < n/2 or a[i] > ((3*n)/4)):
        a[i] = -a[i]
a

3.92 µs ± 59.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Вправа 18. Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99.
Визначити кількість унікальних чисел в послідовності.

In [17]:
%%timeit
#упражнение 18 numpy
import numpy as np
n,summ = 30,0
a = np.random.randint(0,99,n)
for i in range(len(a)):
    temp = 0
    for j in range(len(a)):
        if (i != j and a[i] == a[j]):
            temp = 1
            break
    if (temp == 0):
        summ += 1
    temp = 0
a, "уніикальних чисел: ", summ

234 µs ± 11.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [18]:
%%timeit
import random
#упражнение 18
n,summ = 30,0
a = [random.randint(0,99) for i in range(n)] 
for i in range(len(a)):
    temp = 0
    for j in range(len(a)):
        if (i != j and a[i] == a[j]):
            temp = 1
            break
    if (temp == 0):
        summ += 1
    temp = 0
a,"Унікальних чисел: ", summ

155 µs ± 4.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


В цілому numpy трохи повільніший чим звичайних список, через те, що виділяється більше пам'яті для numpy, але якщо потрібно виконувати математичні операції, numpy  підходить тут краще, бо в ньому є зручні встроєні функції

2. Розв’язати систему за допомогою формул Крамера і виконати перевірку за
допомогою:
* a) матричного множення;
* b) оберненої матриці;
* c) функції numpy.linalg.solve().
***
$$2)=\begin{cases}
x_{1} + 5x_{2}+3x_{3}-4x{4}=10,&\\
3x_{1}+x_{2}-2x_{3}=9,&\\
3x_{1}-7x_{2}+10x_{4}=-9,&\\
3x_{2}-5x_{3}= 1
\end{cases}
$$

In [19]:
import numpy as np
n = 4
a = np.array([[1,5,3,-4], [3,1,-2,0],[5,-7,0,10],[0,3,-5,0]])
b = np.array([20,9,-9,1])
print("Набір елементів A: ",a)
print("Набір елементів B: ",b)
x = np.zeros(n, dtype = float)
det = np.linalg.det(a)
print("Детермінант: ",det)
for i in range(n):
    temp = np.copy(a)
    for j in range(n):
        temp[j][i] = b[j]
    x[i] = float(np.linalg.det(temp)/det)
print("Корні рівняння: ",x)
print("Перевірка чреез матричне множення:")
for i in range(n):
    summ = 0
    for j in range(n):
        summ = summ + a[i][j]*x[j]
    print(summ, "==",b[i])
print("Перевірка через обернену матрицю:",np.linalg.inv(a) @ a, "Діагональні елементи дорівнюють одиниці")
print("Перевірка через функцію np.linalg.silve():",np.linalg.solve(a,b))

Набір елементів A:  [[ 1  5  3 -4]
 [ 3  1 -2  0]
 [ 5 -7  0 10]
 [ 0  3 -5  0]]
Набір елементів B:  [20  9 -9  1]
Детермінант:  -630.0000000000001
Корні рівняння:  [ 3.  2.  1. -1.]
Перевірка чреез матричне множення:
19.999999999999996 == 20
8.999999999999993 == 9
-9.0 == -9
0.9999999999999964 == 1
Перевірка через обернену матрицю: [[ 1.00000000e+00 -2.22044605e-16  0.00000000e+00 -2.63677968e-16]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 5.55111512e-17  8.32667268e-17  1.00000000e+00  0.00000000e+00]
 [ 1.11022302e-16  4.44089210e-16  0.00000000e+00  1.00000000e+00]] Діагональні елементи дорівнюють одиниці
Перевірка через функцію np.linalg.silve(): [ 3.  2.  1. -1.]


#### 3.Oбчислити значення матричного виразу:
* а)з використанням універсальних функцій бібліотеки NumPy
* В)за допомогою ітераційних конструкцій (з використанням циклів, спискових включень)

$$(A-B^{2})\cdot(2A+B)де,
A = \left(\begin{array}{c}5&2&0\\ 
10&4&1\\
7&3&2
\end{array}\right)
B=\left(\begin{array}{c}3&6&-1\\
-1&-2&0\\
2&1&3\end{array}\right)
$$

In [20]:
%%timeit
import numpy as np
a = np.array([[5,2,0],[10,4,1],[7,3,2]])
b = np.array([[3,6,-1],[-1,-2,0],[2,1,3]])
(a-b.dot(b))*(2*a+b)

12 µs ± 679 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
%%timeit
n = int(3)
a = [[5,2,0],[10,4,1],[7,3,2]]
b = [[3,6,-1],[-1,-2,0],[2,1,3]]
arr_bb = [[0]*3,[0]*3,[0]*3]
arr_x = [[0]*3,[0]*3,[0]*3]
for i in range(n):
    for j in range(n):
        for k in range(n):
            arr_bb[i][j] += b[i][k] * b[k][j]
        arr_x[i][j] = (a[i][j] - arr_bb[i][j]) * ((a[i][j] * 2) + b[i][j])
arr_x         

19.6 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### Висновок: В даному прикладі робота алгоритму за допомогою універсальної бібліотеки numpy на 100 міктоекунд довше виконується